title: AfricanCOMMONS
description: A platform to showcase re-useable tools built across Africa and the people & organizations building them.

url: https://commons.africa
enforce_ssl: commons.africa

blog_url: https://medium.com/code-for-africa
github_url: https://github.com/CodeForAfrica/AfricanCOMMONS

google_analytics: UA-44795600-36


# Setup Configs
permalink: pretty
source: src
